### ISSUE TITLE
Connecting to SP but not individual data

### ISSUE THREAD

**Issue by jarichardsonccbf** [LukasK13/sharepointr#6]
I am able to successfully connect to sharepoint and can see the lists within:

```
sp_con = sp_connection("https://cocacolaflorida.sharepoint.com/Distribution/", "user@company.com", "pw", Office365 = T)

lists = sp_getLists(sp_con)
```

calling lists I find the name of the list I want but using ```sp_readeListData``` throws an error

```
data = sp_readListData(sp_con, "Hazardous%20Material%20Disclosure%20Statement", expand = T)
```

```
Error in sp_request(sp_con, "Hazardous%20Material%20Disclosure%20Statement",  : 
  Status Code 400: Request failed.
<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>-1, Microsoft.SharePoint.Client.InvalidClientQueryException</m:code><m:message xml:lang="en-US">The expression "Hazardous Material Disclosure Statement" is not valid.</m:message></m:error>
```

Getting metadata for this same table with ```sp_getListMetadata``` works great.

**Comment by LukasK13** [comment]
Hi @jarichardsonccbf 
Sorry for the late response, but I was very busy with my exams as I am still studying.
Please do not use the encoded list name, so use `listName = "Hazardous Material Disclosure Statement"`. I fixed the mistake in `sp_getLists(sp_con)` which lead to returning encoded list names.
The following should work for you:
```
data = sp_readListData(sp_con, "Hazardous Material Disclosure Statement", expand = T)
```

**Comment by jarichardsonccbf** [comment]
Thanks, I reinstalled sharepointr and reran everything. Still getting hung up on the last step but with a different error now:

```
Error in sp_request(con, if (con$Office365) response$content$odata.nextLink else response$content$d$`__next`) : 
  Status Code 400: Request failed.
<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>-1, Microsoft.SharePoint.Client.InvalidClientQueryException</m:code><m:message xml:lang="en-US">The expression "https:/mycompany.sharepoint.com/Distribution/_api/lists/getbytitle('Hazardous Material Disclosure Statement')/items" is not valid.</m:message></m:error>

```

**Comment by LukasK13** [comment]
Please try setting `expand = FALSE`
```
data = sp_readListData(sp_con, "Hazardous Material Disclosure Statement", expand = F)
```

**Comment by jarichardsonccbf** [comment]
Same error. I took the original error message to our Sharepoint guy (does not know R) and thought it might be an issue with the Sharepoint list being wrapped in CSS? Perhaps this screenshot complete with URL can help diagnose my issue?

<img width="837" alt="sp" src="https://user-images.githubusercontent.com/47988509/74764667-1f0c9100-5250-11ea-8126-d89f55a3f091.png">

**Comment by LukasK13** [comment]
I'm sorry for your problems. As the requests are processed by SharePoints RESTful-API, this issue can't be caused by CSS.
In order to further debug this problem, could you provide me the output of:
```
sp_request(sp_con, URLencode("lists/getbytitle('Hazardous Material Disclosure Statement')/items"))$content$odata.nextLink
```

**Comment by jarichardsonccbf** [comment]
REALLY appreciate your continued assistance on this. There are workarounds to where these data are stored internally but it's a slow turnaround here. 

That line returns
 ````
"https://COMPANYNAME.sharepoint.com/Distribution/_api/lists/getbytitle('Hazardous%20Material%20Disclosure%20Statement')/items?%24skiptoken=Paged%3dTRUE%26p_ID%3d156"
````

**Comment by LukasK13** [comment]
Thank you for your patience. As the error sits within a loop, I need you to complete the connection statement and execute
```
library(sharepointr)
library(jsonlite)
library(xml2)

con = sp_connection("https://company.sharepoint.com", "email", "password", Office365 = T)
listName = "Hazardous Material Disclosure Statement"
listID = NULL
expand = F

response = sp_getListColumns(con, listName = listName, listID = listID, raw = T, hidden = F)
if (response$status_code == 200) {
  columnNamesInternal = if (con$Office365) response$content$value$InternalName[!response$content$value$FromBaseType | response$content$value$InternalName == "Title"] else response$content$d$results$InternalName
  columnNames = if (con$Office365) response$content$value$Title[!response$content$value$FromBaseType | response$content$value$InternalName == "Title"] else response$content$d$results$Title
  response = sp_request(con, URLencode(paste0("lists/", if (!is.null(listName)) paste0("getbytitle('", listName) else paste0("getbyid('", listID), "')/items")))
  if (response$status_code == 200) {
    data = data.frame()
    repeat({
      if (expand && !is.null(unname(unlist(if (con$Office365) response$content$value$FieldValuesAsText else response$content$d$results$FieldValuesAsText)))) {
        items = unname(unlist(if (con$Office365) response$content$value$FieldValuesAsText else response$content$d$results$FieldValuesAsText))
        data_temp = Reduce(rbind, lapply(items, function(item) {
          response = sp_request(con, item)
          if (response$status_code == 200) {
            names(response$content$d) = gsub("_x005f", "", names(response$content$d))
            data = as.data.frame(t(data.frame(unlist(response$content$d[columnNamesInternal]))))
            rownames(data) = NULL
            colnames(data) = columnNames[columnNamesInternal %in% colnames(data)]
            return(data)
          }
        }))
      } else {
        data_temp = as.data.frame(if (con$Office365) response$content$value else response$content$d$results)
        colnames(data_temp) = gsub("^OData_", "", colnames(data_temp))
        data_temp = data_temp[, columnNamesInternal]
        colnames(data_temp) = make.names(columnNames[columnNamesInternal %in% colnames(data_temp)])
      }
      data = if (nrow(data) == 0) data_temp else rbind(
        data.frame(c(data, sapply(colnames(data_temp)[!colnames(data_temp) %in% colnames(data)], function(x) NA))),
        data.frame(c(data_temp, sapply(colnames(data)[!colnames(data) %in% colnames(data_temp)], function(x) NA)))
      )
      if (!is.null(if(con$Office365) response$content$odata.nextLink else response$content$d$`__next`)) {
        print(response$content$odata.nextLink)
        response = sp_request(con, if(con$Office365) response$content$odata.nextLink else response$content$d$`__next`)
        if (response$status_code != 200) stop("Invalid response.")
      } else {
        break
      }
    })
  }
}
```

**Comment by jarichardsonccbf** [comment]
the variable ```response``` returns 

```
Response [https://company.sharepoint.com/distribution/_api/lists/getbytitle('Hazardous%20Material%20Disclosure%20Statement')/fields?$filter=Hidden%20eq%20false%20and%20ReadOnlyField%20eq%20false]
  Date: 2020-02-19 16:20
  Status: 200
  Content-Type: application/json;odata=minimalmetadata;streaming=true;charset=utf-8
  Size: 2 B
Error in readBin(content, character()) : invalid connection
```

and the ifelse chain returns I think the same error I last reported

```
[1]"https://company.sharepoint.com/Distribution/_api/lists/getbytitle('Hazardous%20Material%20Disclosure%20Statement')/items?%24skiptoken=Paged%3dTRUE%26p_ID%3d156"
Error in sp_request(con, request) : Status Code 404: Request failed.
<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>-1, System.ArgumentException</m:code><m:message xml:lang="en-US">List 'Hazardous Material Disclosure Statement' does not exist at site with URL 'https://company.sharepoint.com'.</m:message></m:error>
```

For what it's worth I added "/distribution/" to the end of sharepoint.com which is where the list specifically is. Omitting that returns an error when generating the "response" variable.

Are you able to shed some light on why I can see the column names but not what's within them? That's the most aggravating part for me since it's seeing SOMETHING.

**Comment by LukasK13** [comment]
I am not quite sure what the problem, there is either a problem with the spaces in your list name or with the subpage.
Unfortunately, our admin disabled to feature to create subpages, so I can‘t test that. I created a list with spaces in its title and the request worked for me.
Do you think you could debug the the function `sp_readData` in order to find and fix the problem? I don‘t see a way for me to identify or fix your problem without beeing able to recreate it.

**Comment by LukasK13** [comment]
Could you leave me and future readers a feedback on how you resolved the issue?

**Comment by jarichardsonccbf** [comment]
I actually didn't unfortunately. Tried every combination of spaces and no spaces and directing to the subpage in various places that I could think of. Eventually found a similar Python library which ended up working better for my needs, but convoluted my workflow in the long run..

**Comment by LukasK13** [comment]
I'm sorry to hear that.
